# Generated by Django 5.2.6 on 2025-09-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('completado', 'Completado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('oferta', 'Oferta'), ('edicion', 'Edición limitada'), ('preventa', 'Preventa'), ('ninguno', 'Ninguno')], default='ninguno', max_length=20),
        ),
    ]
